### ISSUE TITLE
Initial Reading

### ISSUE THREAD

**Issue by abose** [aicore/CryptoLib#3]
Reading materials:

* https://en.wikipedia.org/wiki/Secure_communication
* https://en.wikipedia.org/wiki/Cryptography

**Comment by charlypa** [comment]
@adwaith2000 
If you have a Netflix subscription, watch this movie to know how Alan Turing cracked the German enigma machine that was considered uncrackable.

https://www.imdb.com/title/tt2084970/

**Comment by adwaith2000** [comment]
> @adwaith2000
> If you have a Netflix subscription, watch this movie to know how Alan Turing cracked the German enigma machine that was considered uncrackable.
> 
> https://www.imdb.com/title/tt2084970/
